ShootingWebAgent/Controllers/MatchController.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ShootingWebAgent.Areas.Identity.Data;
using ShootingWebAgent.Common;
using ShootingWebAgent.Data;
using ShootingWebAgent.DataModels;
using ShootingWebAgent.SQLite;

namespace ShootingWebAgent.Controllers
{
    public class MatchController : Controller
    {
        private readonly DataDbContext _context;
        private readonly IdentityContext _identityContext;
        private readonly UserManager<ShootingWebAgentUser> _userManager;
        private readonly ILogger<UserController> _logger;

        public class MatchInputModel : Match
        {
            [Required]
            [Display(Name = "Match Name")]
            public new string MatchName { get; set; }
            
            [Required]
            [Display(Name = "Anzahl der Serien")]
            public new int SessionCount { get; set; }
            
            [Required]
            [Display(Name = "Schuss pro Serie")]
            public new int ShotsPerSession { get; set; }
            
            [Required]
            [Display(Name = "Teams")]
            public List<TeamInput> TeamInputs { get; set; }

            public MatchInputModel()
            {
                TeamInputs = new List<TeamInput>();
            }

            public void AddTeamInputs()
            {
                TeamInputs?.Add(new TeamInput());
            }

            public void DeleteTeamInputs()
            {
                TeamInputs?.RemoveAt(0);
            }
        }

        public MatchController(DataDbContext context, UserManager<ShootingWebAgentUser> userManager,
            ILogger<UserController> logger, IdentityContext identityContext)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
            _identityContext = identityContext;
        }

        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated || !User.IsInRole(Roles.PremiumUser.ToString()))
                return Redirect("~/Home");

            var user = _userManager.GetUserAsync(HttpContext.User).Result;

            var matchIds = _identityContext.Users
                .Include(i => i.MatchIds)
                .Single(u => u.Id.Equals(user.Id))
                .MatchIds.Select(id => id.MatchId).ToList();

            var matches = _context.Matches
                .Include(m => m.Teams)
                .Where(m => matchIds.Contains(m.MatchId))
                .ToList();

            return View(matches);
        }

        public IActionResult Create()
        {
            if (!User.Identity.IsAuthenticated || !User.IsInRole(Roles.PremiumUser.ToString()))
                return Redirect("~/Home");

            var match = new MatchInputModel();
            match.AddTeamInputs();
            
            return View(match);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MatchName,SessionCount,ShotsPerSession,TeamInputs")]
            MatchInputModel match)
        {
            if (!User.Identity.IsAuthenticated || !User.IsInRole(Roles.PremiumUser.ToString()))
                return Redirect("~/Home");

            if (ModelState.IsValid)
            {
                var newMatch = new Match()
                {
                    MatchName = match.MatchName,
                    SessionCount = match.SessionCount,
                    ShotsPerSession = match.ShotsPerSession,
                    MatchStatus = MatchStatus.Open,
                    Teams = new List<Team>(),
                    DisagData = new List<DisagJson>(),
                    StatisticModels = new List<StatisticModel>()
                };
                
                foreach (var teamInput in match.TeamInputs)
                {
                    newMatch.Teams.Add(new Team()
                    {
                        TeamName = teamInput.TeamName,
                        TeamHashId = teamInput.TeamName.GetMd5Hash()
                    });
                }
                
                await _context.Matches.AddAsync(newMatch);
                await _context.SaveChangesAsync();
                
                var user = _userManager.GetUserAsync(HttpContext.User).Result;

                var matchIds = _identityContext.Users
                    .Include(i => i.MatchIds)
                    .Single(u => u.Id.Equals(user.Id)).MatchIds;
                
                matchIds.Add(new UserMatches()
                {
                    MatchId = newMatch.MatchId
                });

                await _identityContext.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }

            return View(match);
        }
        
        public IActionResult Edit()
        {
            if (!User.Identity.IsAuthenticated || !User.IsInRole(Roles.PremiumUser.ToString()))
                return Redirect("~/Home");
            
            return View();
        }

        #region Actions

        public void EditMatch(int? id)
        {
            // return LocalRedirect($"/Home/Match?matchId={id}");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddTeam([Bind("TeamInputs")] MatchInputModel match)
        {
            match.AddTeamInputs();
            return PartialView("TeamInputs", match);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteTeam([Bind("TeamInputs")] MatchInputModel match)
        {
            match.DeleteTeamInputs();
            // return PartialView("TeamInputs", match);
            return Ok();
        }

        #endregion
    }
}

ShootingWebAgent/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Logging;
using ShootingWebAgent.Areas.Identity.Data;
using ShootingWebAgent.Hub;

namespace ShootingWebAgent.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ShootingWebAgentUser> _userManager;
        private readonly ILogger<UserController> _logger;
        private readonly IHubContext<UpdateHub> _hubContext;

        public class InputModel
        {
            public string Id { get; set; }
            
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.",
                MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
            
            [Display(Name = "Lockout Enabled")]
            public bool LockoutEnabled { get; set; }
            
            [Display(Name = "Lockout End")]
            public DateTimeOffset? LockoutEnd { get; set; }
            
            [Display(Name = "Email Confirmed")]
            public bool EmailConfirmed { get; set; }

            [Display(Name = "Administrator")]
            public bool IsAdministrator { get; set; }
            
            [Display(Name = "PremiumUser")]
            public bool IsPremiumUser { get; set; }
            
            [Display(Name = "TrialUser")]
            public bool IsTrialUser { get; set; }
        }
        
        public class EditModel : InputModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public new string Email { get; set; }
            
            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.",
                MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Old Password")]
            public string OldPassword { get; set; }
            
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.",
                MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "New Password")]
            public new string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm new password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public new string ConfirmPassword { get; set; }
        }

        public UserController(UserManager<ShootingWebAgentUser> userManager, ILogger<UserController> logger, IHubContext<UpdateHub> hubContext)
        {
            _userManager = userManager;
            _logger = logger;
            _hubContext = hubContext;
        }

        // GET: UserController
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated || !User.IsInRole(Roles.Administrator.ToString()))
                return LocalRedirect("/Identity/Account/Login");

            var userList = new List<InputModel>();
            foreach (var user in _userManager.Users)
            {
                userList.Add(GetInputModelFromUser(user));
            }
            
            return View(userList);
        }

        // GET: UserController/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!User.Identity.IsAuthenticated || !User.IsInRole(Roles.Administrator.ToString()))
                return LocalRedirect("/Identity/Account/Login");

            var user = _userManager.Users.Single(u => u.Id.Equals(id));
            
            return View(GetInputModelFromUser(user));
        }

        // GET: UserController/Create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated || !User.IsInRole(Roles.Administrator.ToString()))
                return LocalRedirect("/Identity/Account/Login");

            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Email,Password,ConfirmPassword,LockoutEnabled,EmailConfirmed,IsAdministrator,IsPremiumUser,IsTrialUser")]
            InputModel inputModel)
        {
            try
            {
                var user = new ShootingWebAgentUser
                {
                    UserName = inputModel.Email,
                    Email = inputModel.Email,
                    LockoutEnabled = inputModel.LockoutEnabled,
                    EmailConfirmed = inputModel.EmailConfirmed
                };
                var result = await _userManager.CreateAsync(user, inputModel.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");
                }
                else
                {
                    _logger.LogError($"Couldn't create user {user.Id}");
                    // return Redirect("~/Home/Error");
                }
                
                IdentityResult addRoleResult;
                if (inputModel.IsAdministrator)
                {
                    addRoleResult = await _userManager.AddToRoleAsync(user, Roles.Administrator.ToString());
                    if (addRoleResult.Succeeded)
                    {
                        _logger.LogInformation($"{Roles.Administrator} Role added to {user.UserName}.");
                    }
                }
                if (inputModel.IsPremiumUser)
                {
                    addRoleResult = await _userManager.AddToRoleAsync(user, Roles.PremiumUser.ToString());
                    if (addRoleResult.Succeeded)
                    {
                        _logger.LogInformation($"{Roles.TrialUser} Role added to {user.UserName}.");
                    }
                }
                if (inputModel.IsTrialUser)
                {
                    addRoleResult = await _userManager.AddToRoleAsync(user, Roles.TrialUser.ToString());
                    if (addRoleResult.Succeeded)
                    {
                        _logger.LogInformation($"{Roles.TrialUser} Role added to {user.UserName}.");
                    }
                }
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(string id)
        {
            if (!User.Identity.IsAuthenticated || !User.IsInRole(Roles.Administrator.ToString()))
                return LocalRedirect("/Identity/Account/Login");

            var user = _userManager.Users.Single(u => u.Id.Equals(id));
            
            return View(GetEditModelFromUser(user));
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, [Bind("Email,Password,ConfirmPassword,LockoutEnabled,EmailConfirmed,IsAdministrator,IsPremiumUser,IsTrialUser")]
            EditModel editModel)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);

                if (editModel.Email?.Length > 0)
                {
                    user.Email = editModel.Email;
                    user.UserName = editModel.Email;
                }

                try
                {
                    if (editModel.Password?.Length > 0)
                    {
                        await _userManager.ChangePasswordAsync(user, editModel.OldPassword, editModel.Password);
                    }
                }
                catch (Exception)
                {
                    ModelState.AddModelError("Password", "Couldn't change Password!");
                    throw;
                }

                user.LockoutEnabled = editModel.LockoutEnabled;
                user.EmailConfirmed = editModel.EmailConfirmed;

                var result = await _userManager.UpdateAsync(user);
                
                if (result.Succeeded)
                {
                    _logger.LogInformation("Changed user credentials");
                }
                else
                {
                    _logger.LogError($"Couldn't change user {user.Id}");
                    return Redirect("~/Home/Error");
                }

                if (!editModel.IsAdministrator.Equals(_userManager.IsInRoleAsync(user,Roles.Administrator.ToString()).Result))
                {
                    if (editModel.IsAdministrator)
                    {
                        await _userManager.AddToRoleAsync(user, Roles.Administrator.ToString());
                    }
                    else
                    {
                        await _userManager.RemoveFromRoleAsync(user, Roles.Administrator.ToString());
                    }
                }
                if (!editModel.IsPremiumUser.Equals(_userManager.IsInRoleAsync(user,Roles.PremiumUser.ToString()).Result))
                {
                    if (editModel.IsPremiumUser)
                    {

ShootingWebAgent/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ShootingWebAgent.Areas.Identity.Data
@inject SignInManager<ShootingWebAgentUser> SignInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ShootingWebAgent</title>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/chartjs/Chart.css" />
    <link href="~/dist/css/bootstrap/tabulator_bootstrap4.min.css" rel="stylesheet">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShootingWebAgent</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    @*                     @if (SignInManager.IsSignedIn(User)) *@
                    @*                     { *@
                    @*                         <li class="nav-item"> *@
                    @*                             <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">Users</a> *@
                    @*                         </li> *@
                    @*                         <li class="nav-item"> *@
                    @*                             <a class="nav-link" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a> *@
                    @*                         </li> *@
                    @*                     } *@
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole(Roles.Administrator.ToString()))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                    }
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole(Roles.PremiumUser.ToString()))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Match" asp-action="Index">Match</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container-fluid" style="width: 100%; margin: 0">
    @*<main role="main" class="pb-3">

        </main>*@
    @RenderBody()
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="errorModalBody">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@if (SignInManager.IsSignedIn(User) && User.IsInRole(Roles.Administrator.ToString()))
{
    <div class="modal fade" id="deleteUserModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="deleteModalBody">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="showError('test','test')">Close</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="return confirmedDelete()">Delete</button>
                </div>
            </div>
        </div>
    </div>
}

<footer class="border-top footer text-muted">
    <div class="container-fluid">
        &copy; 2020 - ShootingWebAgent - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/chartjs/Chart.min.js" asp-append-version="true"></script>
<script src="~/js/layout.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>